export const types= {
    // SIGN_UP : 'USER_SIGN_UP ',
    // LOGIN : 'USER_LOGIN ',
    // LOGOUT : 'LOGOUT',

    LOGIN_START:"LOGIN_START",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILED:"LOGIN_FAILED",
   
    ADD_USER_DETAILS_START:'ADD_USER_DETAILS_START',
    ADD_USER_DETAILS_FAILED:'ADD_USER_DETAILS_FAILED',
    ADD_USER_DETAILS_SUCCESS:'ADD_USER_DETAILS_SUCCESS',
  
    GET_ALL_CONTACTS_START:'GET_ALL_CONTACTS_START',
    GET_ALL_CONTACTS_SUCCESS:'GET_ALL_CONTACTS',
    GET_ALL_CONTACTS_FAILED:'GET_ALL_CONTACTS_FAILED',
  
    GET_USER_DETAILS_START:'GET_USER_DETAILS_START',
    GET_USER_DETAILS_FAILED:'GET_USER_DETAILS_FAILED',
    GET_USER_DETAILS_SUCCESS:'GET_USER_DETAILS_SUCCESS',

    GET_USERS_LIST_START:'GET_USERS_LIST_START',
    GET_USERS_LIST_FAILED:'GET_USERS_LIST_FAILED',
    GET_USERS_LIST_SUCCESS:'GET_USERS_LIST_SUCCESS',

    UPDATE_USER_DETAILS_START:'UPDATE_USER_DETAILS_START',
    UPDATE_USER_DETAILS_FAILED:'UPDATE_USER_DETAILS_FAILED',
    UPDATE_USER_DETAILS_SUCCESS:'UPDATE_USER_DETAILS_SUCCESS',


    GET_PKGTYPE_LIST_START:'GET_PKGTYPE_LIST_START',
    GET_PKGTYPE_LIST_FAILED:'GET_PKGTYPE_LIST_FAILED',
    GET_PKGTYPE_LIST_SUCCESS:'GET_PKGTYPE_LIST_SUCCESS',
  
    UPDATE_PKG_TYPE_START:'UPDATE_PKG_TYPE_START',
    UPDATE_PKG_TYPE_FAILED:'UPDATE_PKG_TYPE_FAILED',
    UPDATE_PKG_TYPE_SUCCESS:'UPDATE_PKG_TYPE_SUCCESS',
  
    DELETE_PKG_TYPE_START:'DELETE_PKG_TYPE_START',
    DELETE_PKG_TYPE_FAILED:'DELETE_PKG_TYPE_FAILED',
    DELETE_PKG_TYPE_SUCCESS:'DELETE_PKG_TYPE_SUCCESS',

    ADD_PKG_TYPE_START:'ADD_PKG_TYPE_START',
    ADD_PKG_TYPE_FAILED:'ADD_PKG_TYPE_FAILED',
    ADD_PKG_TYPE_SUCCESS:'ADD_PKG_TYPE_SUCCESS',

    UPLOAD_IMAGE_START:'UPLOAD_IMAGE_START',
    UPLOAD_IMAGE_FAILED:'UPLOAD_IMAGE_FAILED',
    UPLOAD_IMAGE_SUCCESS:'UPLOAD_IMAGE_SUCCESS',


    GET_PACKAGES_START:'GET_PACKAGES_START',
    GET_PACKAGES_FAILED:'GET_PACKAGES_FAILED',
    GET_PACKAGES_SUCCESS:'GET_PACKAGES_SUCCESS',

    UPDATE_PKG_START:'UPDATE_PKG_START',
    UPDATE_PKG_FAILED:'UPDATE_PKG_FAILED',
    UPDATE_PKG_SUCCESS:'UPDATE_PKG_SUCCESS',

    DELETE_PKG_START:'DELETE_TYPE_START',
    DELETE_PKG_FAILED:'DELETE_TYPE_FAILED',
    DELETE_PKG_SUCCESS:'DELETE_TYPE_SUCCESS',

    ADD_PKG_START:'ADD_PKG_START',
    ADD_PKG_FAILED:'ADD_PKG_FAILED',
    ADD_PKG_SUCCESS:'ADD_PKG_SUCCESS',


    GET_WORKOUT_START:'GET_WORKOUT_START',
    GET_WORKOUT_FAILED:'GET_WORKOUT_FAILED',
    GET_WORKOUT_SUCCESS:'GET_WORKOUT_SUCCESS',

    DELETE_WORKOUT_START:'DELETE_WORKOUT_START',
    DELETE_WORKOUT_FAILED:'DELETE_WORKOUT_FAILED',
    DELETE_WORKOUT_SUCCESS:'DELETE_WORKOUT_SUCCESS',

    UPDATE_WORKOUT_START:'UPDATE_WORKOUT_START',
    UPDATE_WORKOUT_FAILED:'UPDATE_WORKOUT_FAILED',
    UPDATE_WORKOUT_SUCCESS:'UPDATE_WORKOUT_SUCCESS',

    ADD_WORKOUT_START:'ADD_WORKOUT_START',
    ADD_WORKOUT_FAILED:'ADD_WORKOUT_FAILED',
    ADD_WORKOUT_SUCCESS:'ADD_WORKOUT_SUCCESS',

  
    GET_TRAINERS_START:'GET_TRAINERS_START',
    GET_TRAINERS_FAILED:'GET_TRAINERS_FAILED',
    GET_TRAINERS_SUCCESS:'GET_TRAINERS_SUCCESS',

    UPDATE_TRAINER_STATUS_START:'UPDATE_TRAINER_STATUS_START',
    UPDATE_TRAINER_STATUS_FAILED:'UPDATE_TRAINER_STATUS_FAILED',
    UPDATE_TRAINER_STATUS_SUCCESS:'UPDATE_TRAINER_STATUS_SUCCESS',

    SHOW_TOAST:'SHOW_TOAST',
    HIDE_TOAST:'HIDE_TOAST',

  
  }